name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at 00:00 UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make a change
      run: |
        date > date.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '23f3003400@ds.study.iitm.ac.in'
        git add .
        git commit -m "Daily commit: $(date)"
        git push
